apiVersion: v1
kind: PersistentVolume
metadata:
  name: dubhe-pv-nfs
  # pv是集群级别的资源，不属于任何ns
  labels:
    cluster: k8s4dubhe
spec:
  capacity: 
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs: # nfs服务器
    path: /opt/nfs-dirs/dubhe-nfs-with-pv
    # 挂载位置
    server: 192.168.3.196
    #服务器地址
